pipeline:
  docker:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: terryliao0629/drone
    secrets: [ docker_username, docker_password ]
    registry: https://hub.docker.com/r/terryliao0629/
